// Package gitlab emits GitLab CI YAML from a compile.Plan.
// Output is byte-deterministic: same Plan → identical YAML.
package gitlab

import (
	"bytes"
	"fmt"
	"sort"

	"github.com/kilupskalvis/jerry/internal/compile"
	"github.com/kilupskalvis/jerry/internal/spec"
)

// Emit transforms a Plan into a single GitLab CI YAML file.
// All workflows share one .gitlab-ci-jerry.yml with separate jobs.
func Emit(plan *compile.Plan) ([]compile.GeneratedFile, error) {
	var b bytes.Buffer

	fmt.Fprintf(&b, "# GENERATED BY JERRY v%s — DO NOT EDIT.\n", plan.JerryVersion)
	fmt.Fprintf(&b, "# Edit the spec and run `jerry generate --backend gitlab`. CI fails on drift.\n\n")

	var stages []string
	stages = append(stages, "preamble")
	for _, pw := range plan.Workflows {
		for i, step := range pw.Steps {
			stages = append(stages, fmt.Sprintf("%s-%d-%s", pw.Name, i, step.Label))
		}
	}

	fmt.Fprintf(&b, "stages:\n")
	for _, s := range stages {
		fmt.Fprintf(&b, "  - %s\n", s)
	}
	fmt.Fprintf(&b, "\n")

	emitPreamble(&b, plan)

	for _, pw := range plan.Workflows {
		emitWorkflowJobs(&b, pw, plan)
	}

	return []compile.GeneratedFile{
		{Path: ".gitlab-ci-jerry.yml", Content: b.Bytes()},
	}, nil
}

func emitPreamble(b *bytes.Buffer, plan *compile.Plan) {
	fmt.Fprintf(b, "jerry-install:\n")
	fmt.Fprintf(b, "  stage: preamble\n")
	fmt.Fprintf(b, "  variables:\n")
	fmt.Fprintf(b, "    GIT_DEPTH: 0\n")

	var script []string
	script = append(script, fmt.Sprintf("curl -sSL https://jerry.dev/install.sh | sh -s -- --version v%s", plan.JerryVersion))

	if plan.Lock != nil {
		names := make([]string, 0, len(plan.Lock.Runtimes))
		for name := range plan.Lock.Runtimes {
			names = append(names, name)
		}
		sort.Strings(names)
		for _, name := range names {
			rt := plan.Lock.Runtimes[name]
			script = append(script, fmt.Sprintf("npm install -g %s@%s", rt.Package, rt.Version))
		}
	}

	script = append(script, "jerry generate --check")

	fmt.Fprintf(b, "  script:\n")
	for _, line := range script {
		fmt.Fprintf(b, "    - %s\n", line)
	}
	fmt.Fprintf(b, "\n")
}

func emitWorkflowJobs(b *bytes.Buffer, pw compile.PlannedWorkflow, plan *compile.Plan) {
	prevJob := "jerry-install"
	for i, step := range pw.Steps {
		stage := fmt.Sprintf("%s-%d-%s", pw.Name, i, step.Label)
		jobName := fmt.Sprintf("jerry-%s-%s", pw.Name, step.Label)

		fmt.Fprintf(b, "%s:\n", jobName)
		fmt.Fprintf(b, "  stage: %s\n", stage)
		fmt.Fprintf(b, "  needs: [\"%s\"]\n", prevJob)

		fmt.Fprintf(b, "  variables:\n")
		fmt.Fprintf(b, "    GIT_DEPTH: 0\n")
		for _, name := range step.EnvNames {
			fmt.Fprintf(b, "    %s: $%s\n", name, name)
		}

		if step.TimeoutMinutes > 0 {
			fmt.Fprintf(b, "  timeout: %d minutes\n", step.TimeoutMinutes)
		}

		emitRules(b, pw.Triggers)

		if step.Retries > 0 {
			emitRetryScript(b, step)
		} else {
			fmt.Fprintf(b, "  script:\n")
			fmt.Fprintf(b, "    - %s\n", step.Command)
		}

		fmt.Fprintf(b, "\n")
		prevJob = jobName
	}
}

func emitRules(b *bytes.Buffer, t spec.Triggers) {
	fmt.Fprintf(b, "  rules:\n")
	if t.PullRequest != nil {
		fmt.Fprintf(b, "    - if: $CI_PIPELINE_SOURCE == \"merge_request_event\"\n")
	}
	if t.Push != nil {
		if len(t.Push.Branches) > 0 {
			for _, branch := range t.Push.Branches {
				fmt.Fprintf(b, "    - if: $CI_COMMIT_BRANCH == \"%s\"\n", branch)
			}
		} else {
			fmt.Fprintf(b, "    - if: $CI_COMMIT_BRANCH\n")
		}
	}
	if t.Dispatch != nil {
		fmt.Fprintf(b, "    - if: $CI_PIPELINE_SOURCE == \"trigger\"\n")
	}
	if t.Schedule != nil {
		fmt.Fprintf(b, "    - if: $CI_PIPELINE_SOURCE == \"schedule\"\n")
	}
}

func emitRetryScript(b *bytes.Buffer, s compile.PlannedStep) {
	// GitLab's native retry doesn't filter by exit code, so we use
	// the same wrapper script approach as GitHub.
	fmt.Fprintf(b, "  script:\n")
	fmt.Fprintf(b, "    - |\n")
	fmt.Fprintf(b, "      attempt=0\n")
	fmt.Fprintf(b, "      max_attempts=%d\n", s.Retries+1)
	fmt.Fprintf(b, "      while [ \"$attempt\" -lt \"$max_attempts\" ]; do\n")
	fmt.Fprintf(b, "        attempt=$((attempt + 1))\n")
	fmt.Fprintf(b, "        %s && exit 0\n", s.Command)
	fmt.Fprintf(b, "        rc=$?\n")
	fmt.Fprintf(b, "        if [ \"$rc\" -eq 2 ] || [ \"$rc\" -eq 4 ]; then exit \"$rc\"; fi\n")
	fmt.Fprintf(b, "        if [ \"$attempt\" -lt \"$max_attempts\" ]; then\n")
	fmt.Fprintf(b, "          echo \"Retry $attempt/$max_attempts (exit $rc)\"\n")
	fmt.Fprintf(b, "        else\n")
	fmt.Fprintf(b, "          exit \"$rc\"\n")
	fmt.Fprintf(b, "        fi\n")
	fmt.Fprintf(b, "      done\n")
}
