// Package github emits GitHub Actions workflow YAML from a compile.Plan.
// Output is byte-deterministic: same Plan → identical YAML.
package github

import (
	"bytes"
	"fmt"
	"sort"
	"strings"

	"github.com/kilupskalvis/jerry/internal/compile"
	"github.com/kilupskalvis/jerry/internal/spec"
)

// Emit transforms a Plan into GitHub Actions YAML files.
// One file per workflow: .github/workflows/jerry-<name>.yml.
func Emit(plan *compile.Plan) ([]compile.GeneratedFile, error) {
	var out []compile.GeneratedFile
	for _, pw := range plan.Workflows {
		content, err := emitWorkflow(pw, plan)
		if err != nil {
			return nil, fmt.Errorf("emitting workflow %q: %w", pw.Name, err)
		}
		out = append(out, compile.GeneratedFile{
			Path:    fmt.Sprintf(".github/workflows/jerry-%s.yml", pw.Name),
			Content: content,
		})
	}
	return out, nil
}

func emitWorkflow(pw compile.PlannedWorkflow, plan *compile.Plan) ([]byte, error) {
	var b bytes.Buffer

	fmt.Fprintf(&b, "# GENERATED BY JERRY v%s FROM .jerry/%s/ — DO NOT EDIT.\n", plan.JerryVersion, pw.Name)
	fmt.Fprintf(&b, "# Edit the spec and run `jerry generate`. CI fails on drift.\n")

	emitTriggers(&b, pw.Triggers)
	fmt.Fprintf(&b, "jobs:\n")
	fmt.Fprintf(&b, "  %s:\n", pw.Name)
	fmt.Fprintf(&b, "    runs-on: ubuntu-latest\n")
	fmt.Fprintf(&b, "    steps:\n")

	emitPreamble(&b, plan)

	for _, step := range pw.Steps {
		emitStep(&b, step)
	}

	return b.Bytes(), nil
}

func emitPreamble(b *bytes.Buffer, plan *compile.Plan) {
	fmt.Fprintf(b, "      - name: Checkout\n")
	fmt.Fprintf(b, "        uses: actions/checkout@v4\n")
	fmt.Fprintf(b, "        with:\n")
	fmt.Fprintf(b, "          fetch-depth: 0\n")

	fmt.Fprintf(b, "      - name: Install Jerry\n")
	fmt.Fprintf(b, "        run: curl -sSL https://jerry.dev/install.sh | sh -s -- --version v%s\n", plan.JerryVersion)

	if plan.Lock != nil {
		names := make([]string, 0, len(plan.Lock.Runtimes))
		for name := range plan.Lock.Runtimes {
			names = append(names, name)
		}
		sort.Strings(names)
		for _, name := range names {
			rt := plan.Lock.Runtimes[name]
			fmt.Fprintf(b, "      - name: Install %s\n", name)
			fmt.Fprintf(b, "        run: npm install -g %s@%s\n", rt.Package, rt.Version)
		}
	}

	fmt.Fprintf(b, "      - name: Drift check\n")
	fmt.Fprintf(b, "        run: jerry generate --check\n")
}

func emitTriggers(b *bytes.Buffer, t spec.Triggers) {
	fmt.Fprintf(b, "on:\n")
	if t.PullRequest != nil {
		fmt.Fprintf(b, "  pull_request:\n")
		if len(t.PullRequest.Types) > 0 {
			fmt.Fprintf(b, "    types: [%s]\n", strings.Join(t.PullRequest.Types, ", "))
		}
	}
	if t.Push != nil {
		fmt.Fprintf(b, "  push:\n")
		if len(t.Push.Branches) > 0 {
			fmt.Fprintf(b, "    branches: [%s]\n", strings.Join(t.Push.Branches, ", "))
		}
	}
	if t.Dispatch != nil {
		fmt.Fprintf(b, "  repository_dispatch:\n")
		if len(t.Dispatch.Types) > 0 {
			fmt.Fprintf(b, "    types: [%s]\n", strings.Join(t.Dispatch.Types, ", "))
		}
	}
	if t.Schedule != nil {
		fmt.Fprintf(b, "  schedule:\n")
		fmt.Fprintf(b, "    - cron: '%s'\n", t.Schedule.Cron)
	}
}

func emitStep(b *bytes.Buffer, s compile.PlannedStep) {
	fmt.Fprintf(b, "      - name: %s\n", s.Label)

	if s.TimeoutMinutes > 0 {
		fmt.Fprintf(b, "        timeout-minutes: %d\n", s.TimeoutMinutes)
	}

	if len(s.EnvNames) > 0 {
		fmt.Fprintf(b, "        env:\n")
		for _, name := range s.EnvNames {
			fmt.Fprintf(b, "          %s: ${{ secrets.%s }}\n", name, name)
		}
	}

	if s.Retries > 0 {
		emitRetryRun(b, s)
	} else {
		fmt.Fprintf(b, "        run: %s\n", s.Command)
	}
}

func emitRetryRun(b *bytes.Buffer, s compile.PlannedStep) {
	fmt.Fprintf(b, "        run: |\n")
	fmt.Fprintf(b, "          attempt=0\n")
	fmt.Fprintf(b, "          max_attempts=%d\n", s.Retries+1)
	fmt.Fprintf(b, "          while [ \"$attempt\" -lt \"$max_attempts\" ]; do\n")
	fmt.Fprintf(b, "            attempt=$((attempt + 1))\n")
	fmt.Fprintf(b, "            %s && exit 0\n", s.Command)
	fmt.Fprintf(b, "            rc=$?\n")
	fmt.Fprintf(b, "            if [ \"$rc\" -eq 2 ] || [ \"$rc\" -eq 4 ]; then exit \"$rc\"; fi\n")
	fmt.Fprintf(b, "            if [ \"$attempt\" -lt \"$max_attempts\" ]; then\n")
	fmt.Fprintf(b, "              echo \"Retry $attempt/$max_attempts (exit $rc)\"\n")
	fmt.Fprintf(b, "            else\n")
	fmt.Fprintf(b, "              exit \"$rc\"\n")
	fmt.Fprintf(b, "            fi\n")
	fmt.Fprintf(b, "          done\n")
}
