// Package github emits GitHub Actions workflow YAML from a compile.Plan.
// Output is byte-deterministic: same Plan → identical YAML.
package github

import (
	"bytes"
	"fmt"
	"strings"

	"github.com/kilupskalvis/jerry/internal/compile"
	"github.com/kilupskalvis/jerry/internal/spec"
)

// Emit transforms a Plan into GitHub Actions YAML files.
func Emit(plan *compile.Plan) ([]compile.GeneratedFile, error) {
	var out []compile.GeneratedFile
	for _, f := range plan.Files {
		content, err := emitFile(f, plan.JerryVersion)
		if err != nil {
			return nil, fmt.Errorf("emitting %s: %w", f.Path, err)
		}
		out = append(out, compile.GeneratedFile{Path: f.Path, Content: content})
	}
	return out, nil
}

func emitFile(f compile.PlannedFile, jerryVersion string) ([]byte, error) {
	var b bytes.Buffer

	wfName := strings.TrimPrefix(f.Path, ".github/workflows/jerry-")
	wfName = strings.TrimSuffix(wfName, ".yml")

	fmt.Fprintf(&b, "# GENERATED BY JERRY v%s FROM .jerry/%s/ — DO NOT EDIT.\n", jerryVersion, wfName)
	fmt.Fprintf(&b, "# Edit the spec and run `jerry generate`. CI fails on drift.\n")

	if len(f.Jobs) == 0 {
		return b.Bytes(), nil
	}

	job := f.Jobs[0]

	emitTriggers(&b, job.Triggers)
	fmt.Fprintf(&b, "jobs:\n")
	fmt.Fprintf(&b, "  %s:\n", job.Name)
	fmt.Fprintf(&b, "    runs-on: ubuntu-latest\n")
	fmt.Fprintf(&b, "    steps:\n")

	for _, step := range job.Steps {
		emitStep(&b, step)
	}

	return b.Bytes(), nil
}

func emitTriggers(b *bytes.Buffer, t spec.Triggers) {
	fmt.Fprintf(b, "on:\n")
	if t.PullRequest != nil {
		fmt.Fprintf(b, "  pull_request:\n")
		if len(t.PullRequest.Types) > 0 {
			fmt.Fprintf(b, "    types: [%s]\n", strings.Join(t.PullRequest.Types, ", "))
		}
	}
	if t.Push != nil {
		fmt.Fprintf(b, "  push:\n")
		if len(t.Push.Branches) > 0 {
			fmt.Fprintf(b, "    branches: [%s]\n", strings.Join(t.Push.Branches, ", "))
		}
	}
	if t.Dispatch != nil {
		fmt.Fprintf(b, "  repository_dispatch:\n")
		if len(t.Dispatch.Types) > 0 {
			fmt.Fprintf(b, "    types: [%s]\n", strings.Join(t.Dispatch.Types, ", "))
		}
	}
	if t.Schedule != nil {
		fmt.Fprintf(b, "  schedule:\n")
		fmt.Fprintf(b, "    - cron: '%s'\n", t.Schedule.Cron)
	}
}

func emitStep(b *bytes.Buffer, s compile.PlannedStep) {
	fmt.Fprintf(b, "      - name: %s\n", s.Label)

	if s.IsPreamble && strings.Contains(s.Command, "@") && !strings.Contains(s.Command, " ") {
		fmt.Fprintf(b, "        uses: %s\n", s.Command)
		if s.Label == "Checkout" {
			fmt.Fprintf(b, "        with:\n")
			fmt.Fprintf(b, "          fetch-depth: 0\n")
		}
		return
	}

	if s.TimeoutMinutes > 0 {
		fmt.Fprintf(b, "        timeout-minutes: %d\n", s.TimeoutMinutes)
	}

	if len(s.EnvRefs) > 0 {
		fmt.Fprintf(b, "        env:\n")
		for _, ref := range s.EnvRefs {
			fmt.Fprintf(b, "          %s: %s\n", ref.Name, ref.SecretRef)
		}
	}

	if s.Retries > 0 {
		emitRetryRun(b, s)
	} else {
		fmt.Fprintf(b, "        run: %s\n", s.Command)
	}
}

func emitRetryRun(b *bytes.Buffer, s compile.PlannedStep) {
	fmt.Fprintf(b, "        run: |\n")
	fmt.Fprintf(b, "          attempt=0\n")
	fmt.Fprintf(b, "          max_attempts=%d\n", s.Retries+1)
	fmt.Fprintf(b, "          while [ \"$attempt\" -lt \"$max_attempts\" ]; do\n")
	fmt.Fprintf(b, "            attempt=$((attempt + 1))\n")
	fmt.Fprintf(b, "            %s && exit 0\n", s.Command)
	fmt.Fprintf(b, "            rc=$?\n")
	fmt.Fprintf(b, "            if [ \"$rc\" -eq 2 ] || [ \"$rc\" -eq 4 ]; then exit \"$rc\"; fi\n")
	fmt.Fprintf(b, "            if [ \"$attempt\" -lt \"$max_attempts\" ]; then\n")
	fmt.Fprintf(b, "              echo \"Retry $attempt/$max_attempts (exit $rc)\"\n")
	fmt.Fprintf(b, "            else\n")
	fmt.Fprintf(b, "              exit \"$rc\"\n")
	fmt.Fprintf(b, "            fi\n")
	fmt.Fprintf(b, "          done\n")
}
