#!/bin/sh
# Creates a branch, commits generated files, and opens a GitHub PR.
# Requires: GITHUB_TOKEN, git, gh CLI
# Reads: MOTIF_CONTEXT_FILE for trigger data

set -e

INTENT="${MOTIF_INTENT:-motif-generated}"
SAFE_INTENT=$(echo "$INTENT" | tr ' ' '-' | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9-]//g' | head -c 50)
BRANCH="motif/${SAFE_INTENT}-$(date +%s)"
RUN_ID="${MOTIF_RUN_ID:-unknown}"

# Check for changes
if git diff --quiet HEAD; then
    echo '{"status": "no_changes", "message": "No files were modified"}'
    exit 0
fi

# Create branch and commit
git config user.name "Motif Bot"
git config user.email "motif@noreply.github.com"
git checkout -b "$BRANCH"
git add -A
git commit -m "feat: ${INTENT}

Generated by Motif (run: ${RUN_ID})"

# Push and create PR
git push origin "$BRANCH"
PR_URL=$(gh pr create \
    --title "$INTENT" \
    --body "Generated by Motif (run: \`${RUN_ID}\`)" \
    --base main 2>&1)

echo "{\"status\": \"created\", \"pr_url\": \"${PR_URL}\", \"branch\": \"${BRANCH}\"}"
